name: 'Terraform validate'

on:
  push:
    branches:
      - '**'

jobs:
  terraform_validate:
    name: 'terraform_validate'
    runs-on: ubuntu-latest
    env:
      TERRAFORM_VERSION: 1.3.9
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: 'setup Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: 'Terraform - validate'
        run: |
          terraform init -reconfigure
          terraform validate
